version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./form_system.db:/app/form_system.db
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-this
    restart: unless-stopped

networks:
  default:
    name: form-system-network
